import csv
import json
import re
import unicodedata
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent
rows = list(csv.DictReader((ROOT.parent / 'fontes/ids-munduruku-original.tsv').open(), delimiter='\t'))
translations = json.loads((ROOT / 'traducoes-ids.json').read_text())
assert len(rows) == 437
assert all(r['chapter_id'] + '.' + r['entry_id'] in translations for r in rows)

themes = [
('Território, água, céu e fogo', 'Separe substâncias, lugares e fenômenos. Água e rio aparecem com uma forma coincidente, mas os registros não fornecem toda a distribuição contextual. Árvore e madeira também compartilham uma sequência. Monte uma rede com ligações nomeadas: lugar, material, fenômeno atmosférico e processo. Terra como território e solo como material precisam permanecer distinguíveis nas perguntas, mesmo quando as formas se aproximam. A presença de entradas para mar ou gelo não demonstra frequência local nem centralidade cultural: este é um instrumento de comparação lexical. Ao estudar fogo, fumaça, cinza e lenha, conserve as relações do campo sem tratá-las como uma única palavra. A atividade sobre acender e queimar precisa distinguir processo intransitivo de ação sobre algo; o registro lexical não contém sozinho todos os participantes de uma oração.'),
('Pessoas, parentesco e referência', 'Separe nomes de pessoas, relações de parentesco e referência pessoal. Homem e mulher são conceitos lexicais; eu e tu/você dependem do papel no ato de fala. Nós inclusivo inclui o interlocutor; nós exclusivo o deixa fora. Não escolha entre os dois pela quantidade de pessoas: o critério é participação do interlocutor. Termos de parentesco exigem construção e condições de uso; um equivalente português não fornece o sistema de relações completo. Algumas entradas preservam sinais de dependência que não devem desaparecer na ficha. As formas de terceira pessoa aparecem reunidas no registro comparativo: não use essa lista como afirmação de intercambialidade em todos os contextos. As atividades desta unidade testam entradas e distinções de referência, enquanto o estudo gramatical de posse e pronomes fornecerá os ambientes.'),
('Animais e relações de identificação', 'Organize o repertório sem transformar a lista em uma classificação cultural ou biológica completa. Conceitos como ave, peixe ou verme podem ser amplos. Outros distinguem sexo ou estágio, como galo, galinha e frango. A sequência registrada pode conter mais de um elemento, e sua análise precisa de documentação. Não separe uma expressão em traduções palavra por palavra apenas porque o inglês usa uma palavra. Compare o conceito de animal com exemplos particulares e mantenha a diferença entre categoria ampla e item específico. Ninho e colmeia são objetos associados a animais, mas não são animais. Essa distinção ajuda a recuperar sem misturar natureza do referente e campo temático. Identificação de espécie e usos culturais ficam para documentação própria.'),
('Corpo, funções e estados', 'Esta é uma unidade lexical extensa; divida-a em localização corporal, substâncias, processos e estados. Nome de parte do corpo e expressão de um processo não têm necessariamente a mesma construção. Braço, mão e dedo se relacionam anatomicamente, mas precisam de fichas separadas. Cabelo e pena também precisam conservar o referente indicado na fonte. Algumas formas começam com hífen ou mostram material relacional: não crie construções de posse pela tradução meu. Entradas de saúde não são instruções de tratamento. Curar, medicamento e veneno são conceitos lexicais; conhecer suas formas não fornece orientação médica. Categorias pessoais e de deficiência reproduzem o âmbito da fonte comparativa e precisam de cuidado de uso e revisão de adequação por falantes. Aprenda o registro sem transformá-lo em rótulo dirigido a alguém.'),
('Alimentação, preparo e utensílios', 'Separe a comida, a ação de consumir, o estado do alimento e o utensílio. Comer e beber podem apresentar sobreposição de formas no dataset; isso pede estudo das construções, não uma conclusão de equivalência em toda situação. Cru, maduro, verde e podre são conceitos de estado, e verde neste campo diz respeito à maturação. Não o confunda com o registro de cor em outra unidade. Faca e cortar pertencem a uma rede funcional, mas a existência das duas entradas não monta automaticamente uma oração. Compare fruta e árvore frutífera no repertório de plantas, conservando seus códigos. Nomes de alimentos amplos não permitem deduzir toda a identificação botânica ou culinária. As tarefas iniciais trabalham sentido, forma e relações; frases de preparo precisam de modelos atestados.'),
('Roupa, material e acessórios', 'Distinga o material da peça e da ação de trabalhar o material. Pano, algodão e fio não são nomes intercambiáveis. Costurar é um evento que envolve participantes e instrumento, enquanto roupa e acessórios são referências a objetos. Saia, vestido e calça refletem os conceitos de comparação usados pelo dataset; sua distribuição de uso local não é especificada por essa lista. Observe formas com mais de um elemento e preserve a sequência inteira antes de propor uma segmentação. A familiaridade visual de uma palavra não autoriza atribuir sua história a um empréstimo específico sem documentação. Ao organizar a memória, use três grupos: materiais, peças e acessórios, e acrescente um grupo de processos. Os grupos são um recurso didático editorial, não uma classificação tradicional atribuída ao povo.'),
('Moradia, passagem e iluminação', 'Organize as entradas por lugar, abertura, objeto de repouso e fonte de iluminação. Morar ou habitar não é o mesmo conceito que casa; porta não é o mesmo que abrir; cama não é dormir. Essas redes serão cruzadas com outras unidades para reduzir a dependência da ordem de uma lista. Uma expressão comprida pode ser um registro lexical do objeto inteiro; não traduza suas partes sem análise documentada. Lamparina é uma sequência presente na fonte, mas a aparência conhecida não resolve sua pronúncia ou história de uso. O dataset tem poucos itens neste tema e não representa toda a arquitetura ou toda a vida doméstica Munduruku. Registre essa limitação antes de preparar uma descrição de casa com palavras que a fonte não oferece.'),
('Cultivo, plantas e partes', 'Separe espaço de cultivo, planta, parte vegetal, produto e ação. Campo ou roça e jardim são conceitos do instrumento comparativo; não apresentam sozinhos práticas agrícolas ou distinções culturais locais. Semente, raiz, ramo, folha, flor e casca pedem atenção à dependência nominal indicada nas formas. A mesma aparência gráfica em parte corporal e vegetal pode ser uma pista para análise futura, mas não uma demonstração de sentido universal. O par tabaco e fumar mostra que evento e substância podem ocupar registros relacionados. Bananeira e fruto precisam permanecer diferenciados. Ao recuperar uma forma, conserve o sentido da pergunta; perguntar apenas banana quando o registro é de bananeira muda o objeto. Nenhuma lista aqui pretende identificar todas as espécies conhecidas ou utilizadas pelas comunidades.'),
('Ações sobre objetos e ferramentas', 'Agrupe as ações por resultado ou manipulação: unir e separar, cortar e romper, lavar e modificar uma superfície. Esses agrupamentos são descrições editoriais para memória. Não são classes verbais Munduruku demonstradas apenas pelo sentido português. A fonte apresenta ações e objetos associados, como machado, prego e cola. Um nome de ferramenta não determina sua função numa oração: pode ser instrumento, objeto afetado ou referência independente, conforme a construção. Quebrar e quebrado distinguem evento e estado na categoria de comparação. Rasgar, cortar e perfurar não devem ser reduzidos a fazer um buraco ou fazer uma separação sem observar o conceito exato. As atividades pedem recuperar entradas e comparar limites; o curso verbal deverá acrescentar participantes e paradigmas.'),
('Movimento, deslocamento e transporte', 'Distinga modo de movimento, direção, chegada, transporte de algo e lugar de passagem. Caminhar, nadar e voar descrevem maneiras diferentes; entrar e sair descrevem relações com um limite; chegar destaca um ponto do deslocamento. Carregar e trazer envolvem informação adicional sobre algo transportado, que a entrada isolada não analisa por completo. Caminho e estrada apresentam a mesma sequência no dataset: mantenha os dois conceitos sem concluir toda a distribuição contextual. Canoa e remar fornecem uma associação de estudo, não uma frase pronta. Ao preparar uma cena, use esquemas em português para indicar quem se desloca, o que é levado e qual é o destino; só transforme o esquema numa construção Munduruku quando tiver um modelo documentado. O repertório inclui variantes que não devem ser apagadas.'),
('Posse, troca e circulação de bens', 'Ter, possuir, pegar, agarrar, segurar e obter ocupam conceitos diferentes no instrumento de comparação. Algumas formas coincidem entre registros; outras têm alternativas. Estudar diferenças portuguesas não define automaticamente diferenças gramaticais Munduruku, mas ajuda a formular a pergunta que precisa de contexto. Dar, perder, comprar e pagar envolvem eventos com relações entre participantes; a lista não fornece por si só como marcar cada um. Dinheiro, moeda, comerciante e loja pertencem ao mesmo tema sem compartilhar categoria ou função. O uso atual de palavras registradas numa fonte histórica pode exigir confirmação contemporânea. Não use a presença de conceitos comerciais para inferir uma descrição econômica completa. A unidade trabalha correspondências lexicais e prepara análise de construções de posse e transferência.'),
('Posição, dimensão e configuração', 'Este tema reúne relações espaciais, posturas e propriedades de configuração. Perto e longe dependem de referência contextual; direita e esquerda exigem um ponto de orientação; grande e pequeno dependem do domínio de comparação. Alto como dimensão física não deve ser confundido com tom alto. Longo e alto podem apresentar uma forma coincidente no dataset, mas isso não resolve todo o comportamento das construções. Sentar, deitar e ficar em pé são eventos ou estados de postura nos conceitos da fonte. Círculo e redondo não têm necessariamente a mesma categoria. Preserve a informação indicada em cada pergunta, sem substituir um registro por outro apenas porque parecem relacionados. As formas dependentes precisam permanecer com seus sinais na ficha, e sua combinação com nomes será estudada com dados gramaticais.'),
('Quantidade e distribuição', 'Separe numeral, quantidade vaga, totalidade, preenchimento e exclusividade. Dois e muitos respondem a perguntas diferentes. Cheio e vazio descrevem um estado relativo a um recipiente ou domínio, não uma contagem absoluta. Sozinho e apenas também podem envolver interpretação de participantes ou escopo que a tradução abreviada não mostra. Nós como pronome não deve ser confundido com números de pessoas. A pequena série numeral do dataset não determina capacidade de raciocínio nem limita os recursos que uma comunidade emprega para tratar quantidades. Estude formas sem fazer uma escala de inteligência a partir de uma lista. Quando houver variantes ou uma expressão com mais de uma palavra, conserve o registro inteiro; não trate espaços como prova de análise morfológica completa.'),
('Tempo, duração e calendário', 'Distinga momento, duração, velocidade e idade de um referente. Novo e velho neste campo não equivalem automaticamente aos termos para pessoa jovem ou idosa. Dia e noite são conceitos temporais; amanhã exige um ponto de referência no ato de fala. Rápido e demora não são opostos morfológicos demonstrados apenas por traduções. Registros para ano, verão e inverno pertencem a categorias comparativas e podem compartilhar formas; não transfira automaticamente calendários europeus para práticas locais. A fonte lexical não resolve toda a sazonalidade e seus usos atuais. Relógio é um objeto e não toda a expressão de tempo. Use a rede para organizar perguntas: quando, por quanto tempo, com que velocidade e em que período; construções que respondem a essas perguntas precisam de modelos atestados.'),
('Percepção, cor e propriedades', 'Separe sensação, ação de perceber e propriedade do referente. Ouvir e escutar são conceitos comparativos distintos; sua relação lexical precisa de contexto. Ver e olhar também não devem ser usados como traduções universais um do outro. Branco, preto, vermelho, azul, verde e amarelo são rótulos do dataset; não fornecem sozinhos fronteiras de categorias de cor nem usos culturais. Leve neste tema se refere a peso, e luz em outra unidade se refere a iluminação. Quente, morno e frio pedem perguntas específicas de estado. Molhado e seco, limpo e sujo e duro e liso podem ser relacionados editorialmente, mas não são todos opostos do mesmo tipo. A atividade deve preservar o conceito antes de explorar a estrutura.'),
('Emoção, atitude e avaliação', 'Emoções, ações expressivas e avaliações são relacionadas, mas não idênticas. Alegria e rir não descrevem a mesma categoria; tristeza e chorar também não. A lista não permite diagnosticar sentimentos ou inferir o que alguém pensa apenas por uma forma. Bom, ruim e bonito são conceitos de avaliação que podem exigir construções e contextos distintos. Medo e desejo podem participar de predicados com relações específicas; a entrada não ensina sozinha como apresentar a pessoa que sente ou o objeto do sentimento. Verdade e mentir exigem atenção ao sentido da categoria inglesa. As formas com mais de um elemento devem ser preservadas até que exista análise. Não use palavras de avaliação como insultos em atividades: o foco é interpretar a documentação e aprender as distinções.'),
('Conhecimento, pensamento e perguntas', 'Separe pensar, saber, esquecer e parecer. Essas entradas não são um sistema completo de predicados cognitivos. Como, quando e quem são conceitos de pergunta: seu uso depende da construção e do tipo de informação buscada. A forma lexical de uma palavra interrogativa não monta a pergunta inteira. Não/negação também precisa de escopo e distribuição; uma entrada isolada não pode ser inserida livremente em qualquer frase. Causa aparece como material dependente na fonte, e isso precisa permanecer visível. A categoria traduzida como tolo reflete a fonte comparativa e não é um rótulo recomendável para dirigir-se a pessoas. Ao estudar, prepare esquemas de lacunas de informação em português, e depois procure exemplos Munduruku documentados que preencham esse objetivo.'),
('Voz, fala, leitura e escrita', 'Voz e idioma aparecem com uma sequência coincidente no dataset, o que cria uma pergunta útil sobre referências em contexto. Falar, dizer, cantar e contar história continuam conceitos distintos. Nome é uma referência e não a ação de nomear automaticamente. Papel e caneta são objetos; ler é um evento que precisa de algo lido e de uma construção documentada. Uma expressão longa para ler não deve ser recortada em traduções improvisadas. Estudar o registro de contar história não equivale a receber uma narrativa na língua. O curso de leitura deverá incorporar textos autorizados com progressão real. Este tema prepara o vocabulário e a diferença entre saber o nome da atividade e conseguir realizá-la sobre um texto novo.'),
('Organização política e autoridade', 'O dataset fornece poucos registros neste campo. País, rei ou governante e obedecer são categorias do instrumento de comparação; não descrevem automaticamente formas próprias de organização política Munduruku. A tradução de um conceito externo pode resultar de uma situação histórica de documentação, e seu uso contemporâneo precisa de contexto. Bastão de apoio é um objeto incluído no campo de origem do IDS; a organização editorial da fonte não define uma categoria cultural única. A unidade mantém esses registros para cobertura documental, mas não os apresenta como vocabulário suficiente para discutir política ou autoridade. Ao elaborar uma pergunta futura, diferencie o termo da fonte, a instituição histórica referida e a escolha atual de fala. Não acrescente títulos ou cargos por tradução automática.'),
('Conflito, instrumentos e caça', 'Lutar, soldado, arco, flecha e caçar compartilham o campo temático original do IDS, mas não são equivalentes nem uma descrição de práticas culturais. Caça é um evento que pode exigir participante, alvo e circunstância; a entrada não determina essas construções. Arco e flecha são objetos diferentes e devem ser recuperados separadamente. A presença de soldado não implica que a fonte descreve uma categoria tradicional. Mantenha a distinção entre documentação de uma palavra e interpretação histórica ou etnográfica. As atividades trabalham o que está registrado e evitam fabricar narrativas de conflito. O uso de contextos reais no futuro dependerá de fontes autorizadas e de cuidado com seus sentidos e condições de circulação.'),
('Julgamento e identificação de ação', 'Este campo contém apenas dois registros no arquivo consultado. A escassez de entradas é uma limitação documental, não ausência de conceitos ou práticas na língua. Julgar aparece como expressão registrada e ladrão como referência categorial. Não use essa palavra para atribuir uma acusação a uma pessoa real e não deduza uma descrição completa de normas sociais. A tarefa didática distingue um evento de julgamento e uma referência a alguém, preservando as formas inteiras. Ao ampliar o tema, será necessário buscar fontes pertinentes e contextos, em vez de derivar termos jurídicos portugueses por tradução literal. Uma unidade curta é adequada quando o conjunto de evidências é curto; não deve ser expandida com afirmações culturais que o arquivo não sustenta.'),
('Religião e termos de contato', 'O arquivo consultado apresenta um registro neste campo, templo/igreja. Uma única expressão não representa um sistema religioso nem todos os lugares ou práticas de uma comunidade. Preserve a categoria da fonte e a sequência registrada. Sua aparência pode indicar material associado a contato linguístico, mas a história e a adequação de uso exigem documentação própria. O estudo não utiliza o registro para formular saudações, orações ou narrativas religiosas novas. Uma pergunta de pesquisa pode investigar em quais contextos a expressão aparece e como se distingue de outros lugares, sempre com fontes autorizadas. O tamanho reduzido desta unidade reflete o tamanho do conjunto documentado e precisa continuar explícito, mesmo numa obra extensa.')
]

def key(r):
    return r['chapter_id'] + '.' + r['entry_id']

def form(r):
    return r['Mundurukú_Phonemic']

def alternatives(r):
    return [a.strip() for a in form(r).split(';')]

inverse = defaultdict(list)
for r in rows:
    for a in alternatives(r):
        inverse[unicodedata.normalize('NFC', a)].append(r)

instructions = '''## Como trabalhar as tabelas

Leia primeiro o conceito específico e a forma inteira. O inglês original aparece entre parênteses para conservar o sentido do registro. A coluna de formas é transcrição da fonte, não conversão para escrita prática. Estude um bloco de até seis registros por sessão. Faça as atividades antes de abrir as respostas; depois mude a ordem da recuperação. Os comentários da fonte ficam separados das decisões editoriais.
'''

total_tasks = 0
index = []
for ch in range(1, 23):
    data = [r for r in rows if int(r['chapter_id']) == ch]
    title, explanation = themes[ch - 1]
    number = 96 + ch
    parts = [f'# {number}. Repertório: {title}\n', '## Distinções deste campo\n', explanation + '\n', instructions]
    parts += ['## Registros documentados\n', '| Conceito em português (original inglês) | Forma(s) no IDS | Código |', '|---|---|---|']
    for r in data:
        parts.append(f"| {translations[key(r)]} ({r['meaning']}) | {form(r)} | {key(r)} |")
        index.append({'codigo': key(r), 'conceito': translations[key(r)], 'original': r['meaning'], 'formas': form(r), 'comentario': r['comment'], 'capitulo': number})
    comments = [r for r in data if r['comment'].strip()]
    if comments:
        parts += ['\n## Comentários preservados da fonte\n']
        for r in comments:
            parts.append(f"**IDS {key(r)}.** {r['comment']}\n")
        parts.append('Os comentários acima permanecem no idioma e na forma do arquivo original, incluindo repetições eventualmente presentes. Uma referência a outra língua ou entrada não deve ser transformada em regra de uso produtivo sem conferir a documentação.\n')
    answers = []
    for start in range(0, len(data), 6):
        block = data[start:start + 6]
        batch = start // 6 + 1
        prefix = f'L{ch:02d}.{batch:02d}'
        parts.append(f'\n## Bloco de recuperação {batch}\n')
        first = block[::2]
        second = block[1::2]
        parts.append(f"**{prefix}.1 Recuperação.** Cubra as formas. Recupere uma alternativa documentada para cada conceito: " + '; '.join(f"{translations[key(r)]} ({key(r)})" for r in first) + '. Preserve os sinais.\n')
        answers.append(f"**{prefix}.1** " + '; '.join(translations[key(r)] + ': ' + form(r) for r in first) + '. Qualquer alternativa registrada para o conceito atende à recuperação de uma alternativa; a cópia completa exige o registro inteiro.\n')
        if second:
            parts.append(f"**{prefix}.2 Leitura inversa.** Cubra os conceitos. Identifique o conceito específico de cada registro: " + '; '.join(f"{form(r)} ({key(r)})" for r in reversed(second)) + '. O código delimita a pergunta quando uma forma também aparece em outra entrada.\n')
            answers.append(f"**{prefix}.2** " + '; '.join(f"{key(r)}: {translations[key(r)]}" for r in reversed(second)) + '. A resposta deve preservar a distinção de sentido, não apenas uma palavra portuguesa ambígua.\n')
        target = max(block, key=lambda r: (len(alternatives(r)), len(form(r))))
        parts.append(f"**{prefix}.3 Registro inteiro.** Reescreva de memória o registro {key(target)} ({translations[key(target)]}), mantendo todas as alternativas. Depois indique quantas alternativas a coluna separa por ponto e vírgula. Não conte hífens como alternativas.\n")
        answers.append(f"**{prefix}.3** {form(target)}. A coluna tem {len(alternatives(target))} alternativa(s). Hífens são internos à apresentação de cada forma; não têm a função do ponto e vírgula.\n")
        related = []
        for r in block:
            for a in alternatives(r):
                others = [o for o in inverse[unicodedata.normalize('NFC', a)] if key(o) != key(r)]
                if others:
                    related.append((r, a, others))
        if related:
            r, a, others = related[0]
            o = others[0]
            parts.append(f"**{prefix}.4 Comparação.** A sequência {a} aparece em {key(r)} ({translations[key(r)]}) e em {key(o)} ({translations[key(o)]}). Escreva o que está demonstrado e uma informação de uso que essa coincidência ainda não demonstra.\n")
            answers.append(f"**{prefix}.4** Está demonstrada a coincidência de uma sequência em dois registros. Não está demonstrada intercambialidade de todas as construções ou contextos. A pergunta de uso deve pedir um contexto ou uma distribuição, evitando concluir sinonímia universal.\n")
        elif any('-' in form(r) for r in block):
            r = next(r for r in block if '-' in form(r))
            parts.append(f"**{prefix}.4 Forma e análise.** Observe {form(r)} ({key(r)}). Transcreva os hífens e explique por que sua presença não informa automaticamente o número de sílabas nem todas as combinações produtivas da base.\n")
            answers.append(f"**{prefix}.4** A cópia deve conservar {form(r)}. A fronteira representada pertence à convenção da fonte; organização silábica e produtividade precisam de evidências próprias. Não gerar uma palavra nova apenas juntando trechos do repertório.\n")
        else:
            r = block[0]
            parts.append(f"**{prefix}.4 Limite de uso.** Faça uma ficha de {form(r)} ({key(r)}) com conceito, fonte e uma pergunta sobre construção. A pergunta deve investigar como o item entra numa expressão, sem apresentar uma expressão inventada como resposta.\n")
            answers.append(f"**{prefix}.4** A ficha deve indicar {translations[key(r)]}, IDS {key(r)}, a forma {form(r)} e uma pergunta concreta de distribuição ou construção. A entrada fornece uma correspondência lexical; não valida por si só uma oração nova.\n")
        parts.append(f"**{prefix}.5 Retorno sem ordem.** Misture os códigos deste bloco, recupere os conceitos e depois as formas. Anote somente as diferenças entre a tentativa e a tabela, indicando sinal, alternativa ou sentido perdido.\n")
        answers.append(f"**{prefix}.5** O modelo é a tabela dos códigos " + ', '.join(key(r) for r in block) + '. O registro de erro deve identificar a diferença concreta. Acerto apenas na ordem impressa ainda exige recuperação embaralhada.\n')
        total_tasks += 5 if second else 4
    parts += ['\n## Respostas para conferência posterior\n'] + answers
    parts += ['\n## Fonte e atribuição\n', 'IDS, contribuição 287: Mundurukú Dictionary. Mary Ritchie Key; edição de Key e Comrie; fonte indicada Crofts e Sheffler (1981). Dataset sob CC BY 4.0. Traduções portuguesas dos conceitos, organização e tarefas: esta edição.\n', 'https://ids.clld.org/contributions/287\n', 'https://creativecommons.org/licenses/by/4.0/\n']
    (ROOT / 'capitulos' / f'{number:03d}-lexico-{ch:02d}.md').write_text('\n'.join(parts))

(ROOT / 'indice-lexical.json').write_text(json.dumps(index, ensure_ascii=False, indent=2))
print(json.dumps({'registros': len(index), 'temas': len(themes), 'tarefas': total_tasks}, ensure_ascii=False))
